
package com.training.resources;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Flight", targetNamespace = "http://ifaces.training.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Flight {


    /**
     * 
     * @param src
     * @param dest
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seatAvailable", targetNamespace = "http://ifaces.training.com/", className = "com.training.resources.SeatAvailable")
    @ResponseWrapper(localName = "seatAvailableResponse", targetNamespace = "http://ifaces.training.com/", className = "com.training.resources.SeatAvailableResponse")
    @Action(input = "http://ifaces.training.com/Flight/seatAvailableRequest", output = "http://ifaces.training.com/Flight/seatAvailableResponse")
    public String seatAvailable(
        @WebParam(name = "src", targetNamespace = "")
        String src,
        @WebParam(name = "dest", targetNamespace = "")
        String dest);

}
