
package com.training.clients;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CurrencyConverter", targetNamespace = "http://ifaces.training.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CurrencyConverter {


    /**
     * 
     * @param usd
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dolorToRupees", targetNamespace = "http://ifaces.training.com/", className = "com.training.clients.DolorToRupees")
    @ResponseWrapper(localName = "dolorToRupeesResponse", targetNamespace = "http://ifaces.training.com/", className = "com.training.clients.DolorToRupeesResponse")
    @Action(input = "http://ifaces.training.com/CurrencyConverter/dolorToRupeesRequest", output = "http://ifaces.training.com/CurrencyConverter/dolorToRupeesResponse")
    public double dolorToRupees(
        @WebParam(name = "usd", targetNamespace = "")
        double usd);

}
