
package com.training.resources;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SpiceAWServiceService", targetNamespace = "http://services.training.com/", wsdlLocation = "http://localhost:8080/spice?wsdl")
public class SpiceAWServiceService
    extends Service
{

    private final static URL SPICEAWSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SPICEAWSERVICESERVICE_EXCEPTION;
    private final static QName SPICEAWSERVICESERVICE_QNAME = new QName("http://services.training.com/", "SpiceAWServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/spice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPICEAWSERVICESERVICE_WSDL_LOCATION = url;
        SPICEAWSERVICESERVICE_EXCEPTION = e;
    }

    public SpiceAWServiceService() {
        super(__getWsdlLocation(), SPICEAWSERVICESERVICE_QNAME);
    }

    public SpiceAWServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPICEAWSERVICESERVICE_QNAME, features);
    }

    public SpiceAWServiceService(URL wsdlLocation) {
        super(wsdlLocation, SPICEAWSERVICESERVICE_QNAME);
    }

    public SpiceAWServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPICEAWSERVICESERVICE_QNAME, features);
    }

    public SpiceAWServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpiceAWServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Flight
     */
    @WebEndpoint(name = "SpiceAWServicePort")
    public Flight getSpiceAWServicePort() {
        return super.getPort(new QName("http://services.training.com/", "SpiceAWServicePort"), Flight.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Flight
     */
    @WebEndpoint(name = "SpiceAWServicePort")
    public Flight getSpiceAWServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.training.com/", "SpiceAWServicePort"), Flight.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPICEAWSERVICESERVICE_EXCEPTION!= null) {
            throw SPICEAWSERVICESERVICE_EXCEPTION;
        }
        return SPICEAWSERVICESERVICE_WSDL_LOCATION;
    }

}
